name: "deepseek-r1-distill-qwen-1-5b"
backend: "vllm"

version_policy: {
    latest: {
        num_versions: 1
    }
}

max_batch_size: 0
input: [
    {
        name: "text_input"
        data_type: TYPE_STRING
        format: FORMAT_NONE
        dims: [
            1
        ]
        is_shape_tensor: false
        allow_ragged_batch: false
        optional: false
    },
    {
        name: "stream"
        data_type: TYPE_BOOL
        format: FORMAT_NONE
        dims: [
            1
        ]
        is_shape_tensor: false
        allow_ragged_batch: false
        optional: true
    },
    {
        name: "sampling_parameters"
        data_type: TYPE_STRING
        format: FORMAT_NONE
        dims: [
            1
        ]
        is_shape_tensor: false
        allow_ragged_batch: false
        optional: true
    }
]
output: [
    {
        name: "text_output"
        data_type: TYPE_STRING
        dims: [
            -1
        ]
        label_filename: ""
        is_shape_tensor: false
    }
]
batch_input: []
batch_output: []
optimization: {
    priority: PRIORITY_DEFAULT
    input_pinned_memory: {
        enable: true
    }
    output_pinned_memory: {
        enable: true
    }
    gather_kernel_buffer_threshold: 0
    eager_batching: false
}
instance_group: [
    {
        kind: KIND_MODEL
    }
]
default_model_filename: ""
cc_model_filenames: {}
metric_tags: {}
parameters: {}
model_warmup: []
model_transaction_policy: {
    decoupled: true
}